sonar.projectKey=Python-Testing-Pipeline
sonar.projectName=Python CI/CD Pipeline
sonar.projectVersion=1.0.0

sonar.sources=app
sonar.tests=tests
sonar.language=py

sonar.python.coverage.reportPaths=reports/coverage/coverage.xml
sonar.python.xunit.reportPath=reports/junit/junit.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,reports/**,venv/**,.venv/**
sonar.coverage.exclusions=tests/**,app/__init__.py

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_32fd27cf5c8a1a7064c8d6d0955db6e43c98841d
